token-bot: ""
logger:
  level: "DEBUG" # уровень логирования
  path: "logs" # путь для логирования
  file_write: true # включить запись лог в файл
  rotate: 10 # периодичность логирования
  max_bytes: 100000 # максимальный размер лога
  backup_count: 3 # количество сохраняемых логов
  format_full: false # короткий формат выводит только время-уровень-сообщение, полезен в общих чертах без детализации
